name: Build
on:
  push:
  workflow_call:
    outputs:
      JDK_VERSION:
        value: ${{ jobs.build.outputs.JDK_VERSION }}

jobs:
  build:
    uses: malkusch/github/.github/workflows/maven-build.yml@master
    secrets: inherit

  xxx:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo $GITHUB_EVENT_NAME

